/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece651.calculator;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
